package com.infinity.ai.health.data

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.infinity.ai.data.library.GoneDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * End-to-end verification of the 1 -> 2 migration against a real SQLite database.
 *
 * REQUIRES A DEVICE OR EMULATOR — run with `connectedDebugAndroidTest`. The unit-test
 * suite covers the same migration at the DDL level (see `GoneMigrationsTest`), which is
 * what runs in CI without hardware; this one closes the loop by actually creating a
 * version 1 database, populating it, migrating it, and checking the data survived.
 *
 * This test is only possible because `1.json` was captured. Version 1 originally
 * shipped with `exportSchema = false`, so the old schema had to be regenerated by
 * temporarily pinning the database class back to version 1. Without that file,
 * [MigrationTestHelper] cannot build a v1 database and the upgrade path for existing
 * installs would be untestable.
 */
@RunWith(AndroidJUnit4::class)
class MigrationInstrumentedTest {

    private companion object {
        const val TEST_DB = "migration-test.db"
    }

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        GoneDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    /**
     * The property that matters most for real users: upgrading must not lose the
     * content they already saved.
     */
    @Test
    fun migrate1To2_preservesExistingLibraryData() {
        helper.createDatabase(TEST_DB, 1).use { db ->
            db.execSQL(
                """
                INSERT INTO library_entries (type, title, content, sourceInfo, createdAt)
                VALUES ('NOTE', 'Pre-existing note', 'Body text', 'test', 1700000000000)
                """.trimIndent()
            )
        }

        val db = helper.runMigrationsAndValidate(
            TEST_DB, 2, true, GoneMigrations.MIGRATION_1_2
        )

        db.query("SELECT title, content FROM library_entries").use { c ->
            assertTrue("the pre-existing row was lost during migration", c.moveToFirst())
            assertEquals("Pre-existing note", c.getString(0))
            assertEquals("Body text", c.getString(1))
            assertEquals(1, c.count)
        }
    }

    /** All four health tables must exist and accept writes after migrating. */
    @Test
    fun migrate1To2_createsUsableHealthTables() {
        helper.createDatabase(TEST_DB, 1).close()

        val db = helper.runMigrationsAndValidate(
            TEST_DB, 2, true, GoneMigrations.MIGRATION_1_2
        )

        GoneMigrations.MIGRATION_1_2_NEW_TABLES.forEach { table ->
            db.query(
                "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
                arrayOf(table)
            ).use { c ->
                assertTrue("table `$table` was not created", c.moveToFirst())
            }
        }

        db.execSQL(
            """
            INSERT INTO patients (id, name, age, createdAt)
            VALUES ('p1', 'Test patient', 40, 1700000000000)
            """.trimIndent()
        )
        db.execSQL(
            """
            INSERT INTO vitals_readings (patientId, timestamp, heartRate, spo2, source)
            VALUES ('p1', 1700000000000, 78, 97, 'SIMULATED')
            """.trimIndent()
        )
        db.execSQL(
            """
            INSERT INTO anomaly_events (
                patientId, eventType, severity, riskHeat, riskRespiratory,
                riskCardiovascular, evidenceJson, templateExplanation, status, createdAt
            ) VALUES (
                'p1', 'low_spo2', 'CRITICAL', 10, 80, 40, '{}', 'Template text',
                'ACTIVE', 1700000000000
            )
            """.trimIndent()
        )

        db.query("SELECT COUNT(*) FROM vitals_readings").use { c ->
            c.moveToFirst(); assertEquals(1, c.getInt(0))
        }
        db.query("SELECT COUNT(*) FROM anomaly_events").use { c ->
            c.moveToFirst(); assertEquals(1, c.getInt(0))
        }
    }

    /**
     * Room validates the migrated schema against `2.json` internally when
     * `validateDroppedTables` is true, so reaching this point at all proves the
     * hand-written DDL agrees with the entity definitions.
     */
    @Test
    fun migrate1To2_producesASchemaRoomAccepts() {
        helper.createDatabase(TEST_DB, 1).close()
        val db = helper.runMigrationsAndValidate(
            TEST_DB, 2, true, GoneMigrations.MIGRATION_1_2
        )
        assertTrue(db.isOpen)
    }
}
